classdef test_native_replacements < matlab.unittest.TestCase
    % TEST_NATIVE_REPLACEMENTS Validates the custom native logic
    % against the saved baselines generated by the ITA toolbox.
    
    properties
        SignalObj
        SampleRate = 48000;
        SignalData
        IrObj
        IrData
    end
    
    methods(TestMethodSetup)
        function loadGroundTruth(testCase)
            % Initialize paths and tools
            addpath(genpath(fullfile(pwd, 'src')));
            addpath(genpath(fullfile(pwd, 'Toolboxes')));
            try
                setToolboxes();
            catch
                % Silently catch
            end
            
            % Create the identical base signals used in baseline generation
            t = (0:testCase.SampleRate-1)' / testCase.SampleRate;
            testCase.SignalData = sin(2 * pi * 400 * t);
            
            % Mock the structure of itaAudio
            testCase.SignalObj = struct();
            testCase.SignalObj.time = testCase.SignalData;
            testCase.SignalObj.samplingRate = testCase.SampleRate;
            testCase.SignalObj.nSamples = length(testCase.SignalData);
            testCase.SignalObj.nChannels = 1;
            testCase.SignalObj.trackLength = testCase.SignalObj.nSamples / testCase.SampleRate;
            
            testCase.IrData = zeros(testCase.SampleRate, 1);
            testCase.IrData(1) = 1; % Ideal impulse
            
            testCase.IrObj = struct();
            testCase.IrObj.time = testCase.IrData;
            testCase.IrObj.samplingRate = testCase.SampleRate;
            testCase.IrObj.nSamples = length(testCase.IrData);
            testCase.IrObj.nChannels = 1;
        end
    end
    
    methods(Test)
        function testNormalizeMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_normalize.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_normalize.mat'), 'actVal');
                
                nativeVal = native_normalize_dat(testCase.SignalObj);
                
                % Compare core properties
                testCase.verifyEqual(nativeVal.time, actVal.time, 'AbsTol', 1e-6);
            else
                assumeFail(testCase, 'No baseline file found for normalize.');
            end
        end
        
        function testTimeCropMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_timecrop.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_timecrop.mat'), 'actVal');
                
                nativeVal = native_time_crop(testCase.SignalObj, [0 0.5], 'time');
                
                % Time cropping bounds match
                testCase.verifyEqual(length(nativeVal.time), length(actVal.time), 'RelTol', 1e-3);
            else
                 assumeFail(testCase, 'No baseline file found for time crop.');
            end
        end
        
        function testConvolveMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_convolve.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_convolve.mat'), 'actVal');
                
                nativeVal = native_convolve(testCase.SignalObj, testCase.IrObj);
                
                % Length of convolution array
                testCase.verifyEqual(length(nativeVal.time), length(actVal.time));
            else
                 assumeFail(testCase, 'No baseline file found for convolve.');
            end       
        end
        
        function testTimeWindowMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_timewindow.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_timewindow.mat'), 'actVal');
                
                % ITA baseline is precisely 1-second long (48000 samples). testCase.SignalObj is 20s long.
                shortSig = testCase.SignalObj;
                shortSig.time = shortSig.time(1:48000, :);
                shortSig.nSamples = 48000;
                shortSig.trackLength = 1;
                
                nativeVal = native_time_window(shortSig, [0.4 0.5], 'time', 'hann');
                
                % Strict 1-to-1 math comparison
                % ITA uses hann(), not hanning(). These are different MATLAB functions.
                testCase.verifyEqual(nativeVal.time, actVal.time, 'AbsTol', 1e-12);
            else
                 assumeFail(testCase, 'No baseline file found for time window.');
            end
        end
        
        function testTimeShiftMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_timeshift.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_timeshift.mat'), 'actVal');
                
                [nativeVal, ~] = native_time_shift(testCase.SignalObj, 0.1, 'time');
                
                % Dimension comparison
                testCase.verifyEqual(size(nativeVal.time), size(actVal.time));
                % Strict 1-to-1 array mathematical comparison
                testCase.verifyEqual(nativeVal.time, actVal.time, 'AbsTol', 1e-12);
            else
                 assumeFail(testCase, 'No baseline file found for time shift.');
            end
        end
        
        function testAddMatch(testCase)
            if exist(fullfile(fileparts(mfilename('fullpath')), 'baseline_add.mat'), 'file')
                load(fullfile(fileparts(mfilename('fullpath')), 'baseline_add.mat'), 'actVal');
                
                nativeVal = native_add(testCase.SignalObj, testCase.SignalObj);
                
                % Strict 1-to-1 matching array logic
                testCase.verifyEqual(nativeVal.time, actVal.time, 'AbsTol', 1e-12);
            else
                 assumeFail(testCase, 'No baseline file found for add.');
            end
        end
        
        function testCenterTimeSynthetic(testCase)
            % Because ita_roomacoustics wraps multiple levels of dependencies,
            % we test native_center_time purely against a synthetic known decay
            
            % Generate a synthetic noisy impulse with an exponential tail decay
            fs = 48000;
            t = (0:fs-1)' / fs;
            T20 = 0.5;
            D = exp(-13.8 * t / T20);
            rng(1); % deterministic noise
            noise = 1e-4 * randn(size(t));
            synthIR = D + noise;
            
            irStruct.time = synthIR;
            irStruct.samplingRate = fs;
            irStruct.nSamples = length(synthIR);
            irStruct.nChannels = 1;
            
            cTimeVal = native_center_time(irStruct);
            
            % Known mathematically estimated bounding logic
            testCase.verifyGreaterThanOrEqual(cTimeVal, 0.0);
            testCase.verifyLessThan(cTimeVal, T20); % Must sit within T20 limits natively
        end
    end
end
